version: '3'
# Define services
services:
  # App Services
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - api
  api:
    # Configuration for building the docker image for the service
    build:
      # Use an image built from the specified dockerfile in the current directory.
      context: .
      dockerfile: Dockerfile
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_SAMPLER_TYPE=probabilistic
      - JAEGER_SERVICE_NAME=fibonacci-spiral-matrix-go
      - GIN_MODE=debug
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "5775:5775/udp"
      - "16686:16686"


