// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wired

import (
	"github.com/google/wire"
	"fibonacci-spiral-matrix-go/internal/api/handler"
	provider3 "fibonacci-spiral-matrix-go/internal/api/handler/provider"
	provider2 "fibonacci-spiral-matrix-go/internal/core/repository/provider"
	"fibonacci-spiral-matrix-go/internal/core/services/provider"
)

// Injectors from wire.go:

func InitializeFiboSpiralMatrixHandler() (handler.FiboSpiralMatrixHandler, error) {
	fiboSpiralMatrixService := provider.ProvideFiboSpiralMatrixService()
	fiboSpiralMatrixHandler := provider3.ProvideFiboSpiralMatrixHandler(fiboSpiralMatrixService)
	return fiboSpiralMatrixHandler, nil
}

func InitializeAuthHandler() (handler.AuthHandler, error) {
	authRepository := provider2.ProvideAuthRepository()
	authService := provider.ProvideAuthService(authRepository)
	authHandler := provider3.ProvideAuthHandler(authService)
	return authHandler, nil
}

// wire.go:

var AuthService = wire.NewSet(provider.ProvideAuthService, provider2.ProvideAuthRepository)

func InitializeHealthHandler() handler.HealthHandler {
	return handler.HealthHandler{}
}
